### PR TITLE
Add Adafruit MMA8451 Acceleration Sensor and Example

### PR DESCRIPTION
**Pull request by zeejot**
A simple copy to support this sensor for ODROID-GO

### CODE REVIEW

**Comment by joshua-yang** [comment]
Thank you for your contribution. :)

Looks working fine certainly, but before merging this, could you tell us how did you test the example working?
As you know, we have to make sure this working fine. But we couldn't for now. :)

Giving us simple test environments and that results will be appreciated.

**Comment by zeejot** [comment]
I tested this with my Adafruit MMA8451 sensor without problems. I have also an example where the odroid display is used to display the acceleration values.
I can contribute this too.

**Comment by joshua-yang** [comment]
Sounds great.
As this example runs on ODROID-GO, I think it would be better showing the acceleration values on the display. Could you contribute that too?
Combining that 2 examples including the contributed one would be best. :)

**Comment by zeejot** [comment]
done. example is added.

**Comment by joshua-yang** [comment]
Thank you!
This PR will be merged.

**Pull request merged**
